---
import Layout from "@/layouts/Layout.astro";
---

<Layout
  seoProps={{
    title: "Login via GitHub",
    description: "Login using your GitHub account",
  }}
>
  <div style={{ padding: "24px" }}>
    <div id="content">
      <p>We're logging you in...</p>
    </div>
  </div>
</Layout>

<style is:global>
  a {
    text-decoration: underline;
    font-size: 15px;
    display: block;
    margin-bottom: 8px;
    font-weight: var(--font-weight-medium);
  }
</style>

<script>
  import config from "@/config";
  import { ApiError } from "@/rpc";

  const params = new URL(window.location.href).searchParams;

  const code = params.get("code");

  const redirect = params.get("return_to");
  const loginUrl = `${config.API_URL}/login/github${redirect != null ? `?return_to=${redirect}` : ""}`;

  function unexpectedError() {
    const content = document.getElementById("content");
    if (content != null)
      content.innerHTML = `
        <p>Something has gone wrong from our side. Please try again.</p>
        <a href='${loginUrl}'>Login via GitHub</a>
        <a href='/'>Return home</a>
      `;
  }

  if (code != null) {
    try {
      const resp = await fetch(
        `${config.API_URL}/login/github/callback?code=` + code,
        {
          credentials: "include",
        }
      );

      if (resp.status == 200) {
        if (window.opener != null) {
          window.opener.postMessage({ auth: true }, window.location.origin);
        }
        if (redirect == null) {
          window.close();
        } else window.location.replace(redirect);
      } else {
        switch (resp.status) {
          case 500:
            unexpectedError();
            break;
          default:
            const error = ApiError.parse(await resp.json());
            const content = document.getElementById("content");
            if (content != null)
              content.innerHTML = `
                <p>Couldn't log you in due to an error:</p>
                <p style="color: red;">${error.msg}</p>
                ${error.reason != null ? "<p>Reason: ${error.reason}</p>" : ""}
                <a href='${loginUrl}'>Login via GitHub</a>
                <a href='/'>Return home</a>
              `;
        }
      }
    } catch (e) {
      console.error(e);
      unexpectedError();
    }
  } else {
    unexpectedError();
  }
</script>
